LOCAL_AGENT_PATH = '../../../'

# Pods are shared between the iOS and tvOS app targets via abstract_target.
# Each pod's podspec declares both ios.deployment_target and
# tvos.deployment_target = 12.0, so the same source ships on both platforms.
# NRIMATracker pulls in GoogleAds-IMA-iOS-SDK on iOS and GoogleAds-IMA-tvOS-SDK
# on tvOS automatically.

abstract_target 'NRSampleApp_Shared' do
  use_frameworks!

  pod 'NewRelicVideoAgent', :path => LOCAL_AGENT_PATH
  pod 'NRAVPlayerTracker',  :path => LOCAL_AGENT_PATH
  pod 'NRIMATracker',       :path => LOCAL_AGENT_PATH

  target 'NRSampleApp_iOS' do
    platform :ios, '15.0'
  end

  target 'NRSampleApp_tvOS' do
    platform :tvos, '15.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['TVOS_DEPLOYMENT_TARGET']     = '15.0'
    end
  end
end
